name: Multi-Arch Build

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: dcr.behzadan.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dcr.behzadan.com/reza/behzadan.com-hugo:latest
            dcr.behzadan.com/reza/behzadan.com-hugo:${{ gitea.ref_name }}

